### ISSUE TITLE
Target Framework .Net 5

### ISSUE THREAD

**Issue by antonma** [mrchrisok/OandaV20.2#7]
Hi,

I would like to use this library as Azure Function in the MS Cloud. 
Unfortunately Azure functions do only support .Net Core 3.1 or .Net 5

Any chance you guys could migrate this library to .Net 5 or .Net Core? 

Thank in advance and best regards,
Anton

**Comment by mrchrisok** [comment]
Hi Anton ..
Porting this to .NET is a possibility. 
However, there is no target date for that as of yet.
